=pod

=encoding UTF-8

=head1 NAME

WebGPU::Direct::QuerySet

=head2 Methods

=head3 Destroy (void)

=head3 GetCount (uint32_t)

=head3 GetType (L<WGPUQueryType|WebGPU::Direct::Constants/WGPUQueryType>)

=head3 SetLabel (void)

=over

=item Arguments

=over

=item label (L<WebGPU::Direct::char>)

=back

=back

=head3 Reference (void)

=head3 Release (void)

